language: generic
sudo: required
services:
  - docker
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4
before_install:
  - bash test/travis_install.sh
script:
  - bash test/travis_script.sh
